In [2]:
import pandas as pd

## CSV with no header for data

In [26]:
# read in CC_cleaned.csv
CC_cleaned = pd.read_csv('../Data/CC_cleaned.csv')

# head
CC_cleaned.head()

# get zip_clusters for the zips below using the CC_cleaned.csv dataframe

# zip_lat_lon = {
#     2625: (41.6485, -70.3475),
#     2031: (42.1579, -71.1762),
#     2068: (42.0248, -71.1022),
#     2425: (42.3318, -71.1212),
#     2469: (42.2965, -71.2921),
#     2154: (42.3765, -71.2356)
# }

# print zip_cluster for the zip 2625
print(CC_cleaned[CC_cleaned['ZIP'] == 2625]['zip_cluster'])
print(CC_cleaned[CC_cleaned['ZIP'] == 2031]['zip_cluster'])
print(CC_cleaned[CC_cleaned['ZIP'] == 2068]['zip_cluster'])
print(CC_cleaned[CC_cleaned['ZIP'] == 2425]['zip_cluster'])
print(CC_cleaned[CC_cleaned['ZIP'] == 2469]['zip_cluster'])
print(CC_cleaned[CC_cleaned['ZIP'] == 2154]['zip_cluster'])

1901    2601.0
Name: zip_cluster, dtype: float64
2397    2062.0
Name: zip_cluster, dtype: float64
5451    2375.0
Name: zip_cluster, dtype: float64
7308    2446.0
Name: zip_cluster, dtype: float64
8237    2482.0
Name: zip_cluster, dtype: float64
8364    2453.0
Name: zip_cluster, dtype: float64

In [42]:
# get CC_realtor_merged_cleaned_adjusted.csv
CC_realtor_merged_cleaned_adjusted = pd.read_csv('../Data/CC_realtor_merged_cleaned_adjusted.csv')

# head
CC_realtor_merged_cleaned_adjusted.head()

,ZIP,SOLDPRICE,SQFT,BEDS,BATHS,AGE,DOM,lat,long,zip_cluster,price_multiplier,days_on_market_multiplier,adjusted_sold_price,adjusted_dom
0,2474,410000.0,1368,2,2.0,3,897,42.4202,-71.1565,2474.0,0.492502,0.352941,201925.858031,316.588235
1,2124,327000.0,1850,2,2.5,5,658,42.2918,-71.0717,2124.0,0.753723,1.320000,246467.513766,868.560000
2,2184,331000.0,1469,2,1.0,38,467,42.2093,-70.9963,2184.0,0.660431,0.435897,218602.614649,203.564103
3,1949,580000.0,2945,2,2.5,4,565,42.5942,-71.0130,1949.0,0.621947,1.500000,360729.317692,847.500000
4,2139,1000000.0,2536,3,2.5,3,56,42.3647,-71.1042,2139.0,0.662793,0.240741,662792.730048,13.481481

In [43]:
# get the number of nulls in the dataframe
print(CC_realtor_merged_cleaned_adjusted.isnull().sum())

# get the rows with nulls
print(CC_realtor_merged_cleaned_adjusted[CC_realtor_merged_cleaned_adjusted.isnull().any(axis=1)])

# hard coded zips that are not in the pgeocode database
zip_lat_lon = {
    2625: (41.6485, -70.3475),
    2031: (42.1579, -71.1762),
    2068: (42.0248, -71.1022),
    2425: (42.3318, -71.1212),
    2469: (42.2965, -71.2921),
    2154: (42.3765, -71.2356)
}

# 2601.0
# Name: zip_cluster, dtype: float64
# 2397    2062.0
# Name: zip_cluster, dtype: float64
# 5451    2375.0
# Name: zip_cluster, dtype: float64
# 7308    2446.0
# Name: zip_cluster, dtype: float64
# 8237    2482.0
# Name: zip_cluster, dtype: float64
# 8364    2453.0

# add zip clusters based on the above
CC_realtor_merged_cleaned_adjusted.loc[CC_realtor_merged_cleaned_adjusted['ZIP'] == 2625, 'zip_cluster'] = 2601.0
CC_realtor_merged_cleaned_adjusted.loc[CC_realtor_merged_cleaned_adjusted['ZIP'] == 2031, 'zip_cluster'] = 2062.0
CC_realtor_merged_cleaned_adjusted.loc[CC_realtor_merged_cleaned_adjusted['ZIP'] == 2068, 'zip_cluster'] = 2375.0
CC_realtor_merged_cleaned_adjusted.loc[CC_realtor_merged_cleaned_adjusted['ZIP'] == 2425, 'zip_cluster'] = 2446.0
CC_realtor_merged_cleaned_adjusted.loc[CC_realtor_merged_cleaned_adjusted['ZIP'] == 2469, 'zip_cluster'] = 2482.0
CC_realtor_merged_cleaned_adjusted.loc[CC_realtor_merged_cleaned_adjusted['ZIP'] == 2154, 'zip_cluster'] = 2453.0

# add the lat and long for the hard coded zips
for zip_code, (lat, long) in zip_lat_lon.items():
    CC_realtor_merged_cleaned_adjusted.loc[CC_realtor_merged_cleaned_adjusted['ZIP'] == zip_code, 'lat'] = lat
    CC_realtor_merged_cleaned_adjusted.loc[CC_realtor_merged_cleaned_adjusted['ZIP'] == zip_code, 'long'] = long

ZIP                          0
SOLDPRICE                    0
SQFT                         0
BEDS                         0
BATHS                        0
AGE                          0
DOM                          0
lat                          6
long                         6
zip_cluster                  6
price_multiplier             0
days_on_market_multiplier    0
adjusted_sold_price          0
adjusted_dom                 0
dtype: int64
       ZIP  SOLDPRICE  SQFT  BEDS  BATHS  AGE  DOM  lat  long  zip_cluster  \
1901  2625   203000.0  2261     2    2.5   12   26  NaN   NaN          NaN
2397  2031   130500.0  1503     2    2.5    2  103  NaN   NaN          NaN
5451  2068   166000.0  1600     2    1.5   32  178  NaN   NaN          NaN
7308  2425   599000.0  2400     3    2.5   34   26  NaN   NaN          NaN
8237  2469   169000.0  2160     2    2.5    2  166  NaN   NaN          NaN
8364  2154   400000.0  1900     2    1.5    5  112  NaN   NaN          NaN

      price_multiplier  days_on_market_multiplier  adjusted_sold_price  \
1901          0.676487                   0.988276        137326.846930
2397          0.676487                   0.988276         88281.544455
5451          0.676487                   0.988276        112296.830495
7308          0.676487                   0.988276        405215.671484
8237          0.676487                   0.988276        114326.291287
8364          0.676487                   0.988276        270594.772276

      adjusted_dom
1901     25.695166
2397    101.792390
5451    175.913061
7308     25.695166
8237    164.053754
8364    110.686870

In [44]:
# write that back to a csv
CC_realtor_merged_cleaned_adjusted.to_csv('../Data/CC_realtor_merged_cleaned_adjusted.csv', index=False)

In [36]:
# get nulls of all columns
print(CC_realtor_merged_cleaned_adjusted[CC_realtor_merged_cleaned_adjusted.isnull().any(axis=1)])

Empty DataFrame
Columns: [ZIP, SOLDPRICE, SQFT, BEDS, BATHS, AGE, DOM, lat, long, zip_cluster, price_multiplier, days_on_market_multiplier, adjusted_sold_price, adjusted_dom]
Index: []

In [37]:
# remove ZIP, lat, long, price_multiplier, days_on_market_multiplier, adjusted_sold_price, adjusted_dom, SOLDPRICE
CC_realtor_merged_cleaned_adjusted = CC_realtor_merged_cleaned_adjusted.drop(columns=['ZIP', 'lat', 'long', 'price_multiplier', 'days_on_market_multiplier', 'adjusted_sold_price', 'adjusted_dom', 'SOLDPRICE'])

# one hot encode the zip_cluster column
#CC_realtor_merged_cleaned_adjusted = pd.get_dummies(CC_realtor_merged_cleaned_adjusted, columns=['zip_cluster'])

# set the zip_cluster column to be categorical
CC_realtor_merged_cleaned_adjusted['zip_cluster'] = CC_realtor_merged_cleaned_adjusted['zip_cluster'].astype('category')

# get head 
CC_realtor_merged_cleaned_adjusted.head()

   SQFT  BEDS  BATHS  AGE  DOM zip_cluster
0  1368     2    2.0    3  897      2474.0
1  1850     2    2.5    5  658      2124.0
2  1469     2    1.0   38  467      2184.0
3  2945     2    2.5    4  565      1949.0
4  2536     3    2.5    3   56      2139.0

In [38]:
# check for nulls
CC_realtor_merged_cleaned_adjusted.isnull().sum()

# print the null rows
null_columns = CC_realtor_merged_cleaned_adjusted.columns[CC_realtor_merged_cleaned_adjusted.isnull().any()]
print(CC_realtor_merged_cleaned_adjusted[CC_realtor_merged_cleaned_adjusted.isnull().any(axis=1)])

Empty DataFrame
Columns: [SQFT, BEDS, BATHS, AGE, DOM, zip_cluster]
Index: []

In [39]:
# make DOM the first column, then save to csv with header
# there are a ton of zip_cluster columns, so we can't list them out when indicating the order of the columns otherwise
CC_realtor_merged_cleaned_adjusted = pd.concat([CC_realtor_merged_cleaned_adjusted['DOM'], CC_realtor_merged_cleaned_adjusted.drop(columns=['DOM'])], axis=1)

# change the zip_cluster column to be categorical
CC_realtor_merged_cleaned_adjusted['zip_cluster'] = CC_realtor_merged_cleaned_adjusted['zip_cluster'].astype('category')

# print the column type of the zip_cluster column
print(CC_realtor_merged_cleaned_adjusted['zip_cluster'].dtype)

# save to csv with header
CC_realtor_merged_cleaned_adjusted.to_csv('../Data/baseline_model/CC_baseline_header.csv', index=False)

# save to csv without header
CC_realtor_merged_cleaned_adjusted.to_csv('../Data/baseline_model/CC_baseline_no_header.csv', index=False, header=False)

category

In [14]:
# read in the no header file and check the zip_cluster column type to make sure it's categorical
CC_realtor_merged_cleaned_adjusted_no_header = pd.read_csv('../Data/baseline_model/CC_baseline_header.csv')

# head
print(CC_realtor_merged_cleaned_adjusted_no_header.head())

# check the zip_cluster column type
CC_realtor_merged_cleaned_adjusted_no_header['zip_cluster'].dtype

   DOM  SQFT  BEDS  BATHS  AGE  zip_cluster
0  897  1368     2    2.0    3       2474.0
1  658  1850     2    2.5    5       2124.0
2  467  1469     2    1.0   38       2184.0
3  565  2945     2    2.5    4       1949.0
4   56  2536     3    2.5    3       2139.0

dtype('float64')

## Make a json with a mapping from the zip code to zip code cluster

In [45]:
# get CC_realtor_merged_cleaned_adjusted.csv
CC_realtor_merged_cleaned_adjusted = pd.read_csv('../Data/CC_realtor_merged_cleaned_adjusted.csv')

# head
CC_realtor_merged_cleaned_adjusted.head()

,ZIP,SOLDPRICE,SQFT,BEDS,BATHS,AGE,DOM,lat,long,zip_cluster,price_multiplier,days_on_market_multiplier,adjusted_sold_price,adjusted_dom
0,2474,410000.0,1368,2,2.0,3,897,42.4202,-71.1565,2474.0,0.492502,0.352941,201925.858031,316.588235
1,2124,327000.0,1850,2,2.5,5,658,42.2918,-71.0717,2124.0,0.753723,1.320000,246467.513766,868.560000
2,2184,331000.0,1469,2,1.0,38,467,42.2093,-70.9963,2184.0,0.660431,0.435897,218602.614649,203.564103
3,1949,580000.0,2945,2,2.5,4,565,42.5942,-71.0130,1949.0,0.621947,1.500000,360729.317692,847.500000
4,2139,1000000.0,2536,3,2.5,3,56,42.3647,-71.1042,2139.0,0.662793,0.240741,662792.730048,13.481481

In [46]:
# df with zip code and zip_cluster
zip_cluster_df = CC_realtor_merged_cleaned_adjusted[['ZIP', 'zip_cluster']].drop_duplicates()

# save to json
zip_cluster_df.to_json('../Data/baseline_model/zip_cluster_mapping.json', orient='records')

## Make JSON for the min and max price per zip cluster

In [20]:
# make new df with zip_cluster and min and max price
min_max_price_df = CC_realtor_merged_cleaned_adjusted.groupby('zip_cluster')['SOLDPRICE'].agg(['min', 'max']).reset_index()

# head
min_max_price_df.head()

# save to json
min_max_price_df.to_json('../Data/baseline_model/min_max_price_per_zip_cluster.json', orient='records')